Translate in French igbinary/book.xml
php/doc-fr pull request #166
Opened 2022-02-28 15:59 UTC by moradZahid

2022-02-28 17:22 UTC, Girgias requested changes
Merci pour la contribution!

Quelque changement mineur à faire. :-)

2022-02-28 17:22 UTC, Girgias commented on reference/igbinary/functions/igbinary-unserialize.xml
> +    A la place, un standard d'échange sûr tel que JSON (via <function>json_decode</function> et
```suggestion
    À la place, un standard d'échange sûr tel que JSON (via <function>json_decode</function> et 
```

2022-02-28 17:22 UTC, Girgias commented on reference/igbinary/functions/igbinary-unserialize.xml
> +      <link linkend="object.unserialize">__unserialize()</link> et
```suggestion
      <link linkend="object.unserialize">__unserialize()</link> ou
```
Me semble plus correcte (faut potentiellement corrigé la version anglaise).

2022-02-28 17:22 UTC, Girgias commented on reference/igbinary/functions/igbinary-unserialize.xml
> +  et une erreur <constant>E_NOTICE</constant> ou <constant>E_WARNING</constant> est émise.
Nit indentation

2022-02-28 17:22 UTC, Girgias commented on reference/igbinary/functions/igbinary-unserialize.xml
> +    ou bien en attrapant une erreur <constant>E_NOTICE</constant>.
```suggestion
    ou bien en attrapant un diagnostic <constant>E_NOTICE</constant>.
```
Je préfère diqgnostic à 'erreur' car s'en ai pas vraiment une.

2022-02-28 17:22 UTC, Girgias commented on reference/igbinary/functions/igbinary-unserialize.xml
> +    <member><link linkend="language.oop5.autoload">Autoloading Classes</link></member>
Traduire ceci par "Autochargement de classe" peut être?

2022-02-28 17:22 UTC, Girgias commented on reference/igbinary/book.xml
> +
```suggestion
<?xml version="1.0" encoding="utf-8"?>
<!-- EN-Revision: aa19c140e6be8b9c324c32ace850dfc2911891a2 Maintainer: moradZahid  Status:  -->
<!-- Reviewed: no -->
```
Reviewed c'est pour une relecture et correction orthographique techniquement et pas lors d'une traduction initiale.

IIRC Il faut forcement un user dans le champ maintainer sinon le revcheck bug.
Donc ce chqnge,ent doit être aussi fait sur les autres fichiers.

2022-02-28 18:22 UTC, moradZahid commented on reference/igbinary/functions/igbinary-unserialize.xml
> +  et une erreur <constant>E_NOTICE</constant> ou <constant>E_WARNING</constant> est émise.
Désolé j'étais pas très concentré

2022-02-28 18:37 UTC, moradZahid commented on reference/igbinary/functions/igbinary-unserialize.xml
> +    <member><link linkend="language.oop5.autoload">Autoloading Classes</link></member>
Aïe désolé ça m'a échappé j'ai regardé le lien en français et le titre utilisé est "Auto-chargement de classes". Donc je l'ai gardé si c'est pas génant

2022-02-28 18:44 UTC, moradZahid commented
Merci pour les suggestions.
Je suis vraiment désolés pour les erreurs d'attentions.
J'espère que les changements conviendront

2022-03-01 14:03 UTC, Girgias commented on reference/igbinary/functions/igbinary-unserialize.xml
> +  et une erreur <constant>E_NOTICE</constant> ou <constant>E_WARNING</constant> est émise.
Pas de soucis. :-)

2022-03-01 14:04 UTC, Girgias commented on reference/igbinary/functions/igbinary-unserialize.xml
> +    <member><link linkend="language.oop5.autoload">Autoloading Classes</link></member>
Si c'est comme ça qu'est traduit le titre sur la page originale, autant faire de même ici en effet.

2022-03-01 14:05 UTC, merged