Match
php/doc-fr pull request #20
Opened 2021-02-27 08:35 UTC by SVGAnimate

Hello World,

Je crée un RP pour avoir vos avis sur ma traduction de "match"

"match expression" :
- élement de langage ?
- structure ?
- expression match ?

"identity check" :
- comparaison strict ?
- comparaison à l'identique ?

"weak equality check" :
- égalité faible ?
- comparaison faiblement typé ?

PS : Veuillez m'excuser, je n'ai pas encore porté d'attention sur l'orthographe.

2021-02-27 08:38 UTC, SVGAnimate commented
In response of :
https://bugs.php.net/bug.php?id=80692

PS : I will appreciate having your notes

2021-02-27 12:10 UTC, Girgias requested changes
ça m'a l'air plus ou moins bon, après je suis pas le meilleur en orthographe/conjugaison donc c'est possible qu'il y ait encore des fautes d'accord.

Si possible les lignes devrait aussi faire 80 caractères au maximum (c'est pas une règle stricte mais ça aide quand on regarde des diffs dans un terminal)

2021-02-27 12:10 UTC, Girgias commented on language/control-structures/match.xml
> +    $this->baz => beep(), // beep() isn't called unless $x === $this->baz
Les commentaires doivent être traduit ici

2021-02-27 12:10 UTC, Girgias commented on language/control-structures/match.xml
> +    // Equivalent à ces trois embranchement:
```suggestion
    // Équivalent à ces trois embranchement:
```

2021-02-27 12:10 UTC, Girgias commented on language/control-structures/match.xml
> +  Cette clause correspond à tout ce qui ne correspondait pas auparavant.
L'anglais de base est pas oufisime mais qqch du genre peut être :
```suggestion
  Cette clause est évalué si aucune clause précédente correspondait à la condition fourni. 
```
?

2021-02-27 12:10 UTC, Girgias commented on language/control-structures/match.xml
> +   les expression conditions en utilisant <code>true</code> comme expression soumis.
```suggestion
   les expressions conditionnelles en utilisant <code>true</code> comme expression soumis.
```
Me semble plus correcte

2021-02-27 12:10 UTC, Girgias commented on language/control-structures/match.xml
> +   <title>Embranchement basé sur une plage d'entier</title>
J'avais jamais penser à utiliser le mot `plage` pour ce genre de situation mais c'est très bien vu

2021-02-27 13:07 UTC, villfa requested changes

2021-02-27 13:07 UTC, villfa commented on language/control-structures/match.xml
> +    Plusieurs clause <literal>default</literal> soulèveront une erreur
```suggestion
    Plusieurs clauses <literal>default</literal> soulèveront une erreur
```

2021-02-27 13:07 UTC, villfa commented on language/control-structures/match.xml
> +  <classname>UnhandledMatchError</classname> est soulèvé.
```suggestion
  <classname>UnhandledMatchError</classname> est soulevée.
```

2021-02-27 13:07 UTC, villfa commented on language/control-structures/match.xml
> +  Si l'expression soumis ne correspond à aucun embranchement une erreur
```suggestion
  Si l'expression soumise ne correspond à aucun embranchement une erreur
```

2021-02-27 13:07 UTC, villfa commented on language/control-structures/match.xml
> +  <title>Utilisation de match pour gérer les expressions conditionnels</title>
```suggestion
  <title>Utilisation de match pour gérer les expressions conditionnelles</title>
```

2021-02-27 13:07 UTC, villfa commented on language/control-structures/match.xml
> +   les expression conditions en utilisant <code>true</code> comme expression soumis.
Et aussi `expression soumise` à la fin

2021-02-27 17:42 UTC, villfa commented on language/control-structures/match.xml
> +    // Equivalent à ces trois embranchement:
Aussi : `embranchements` (pluriel)

2021-03-10 21:04 UTC, afilina commented on language/control-structures/match.xml
> +  et c'est un raccourci pour plusieurs embranchement similaire.
```suggestion
  et c'est un raccourci pour plusieurs embranchement similaires. 
```

2021-03-10 21:04 UTC, afilina commented on language/control-structures/match.xml
> +  Cette clause correspond à tout ce qui ne correspondait pas auparavant.
Aussi: `évaluée`, `fournie`

2021-03-10 21:04 UTC, afilina commented on language/control-structures/match.xml
> +  Si l'expression soumis ne correspond à aucun embranchement une erreur
Aussi: `embranchement, `

2021-03-10 21:04 UTC, afilina commented on language/control-structures/match.xml
> +  <title>Exemple d'embranchement manquant.</title>
```suggestion
  <title>Exemple d'embranchement manquant</title>
```

2021-03-11 10:48 UTC, SVGAnimate commented
Bonjour à tous,
Merci de l'intérêt que vous avez porté à ma requête.

J'ai modifier ma branche avec toutes vos corrections.
Je n'ai pas réussi à ajouter de commentaire( "Suggested change") , comme vous.

Si il vous plaît, dites moi comment ajouter une suggestion sur github ?
- Cette clause est évalué si aucune clause précédente correspondait à la condition fourni.
+ Cette clause est évaluée si aucune clause précédente n'a correspondu.

-Equivalent
+Equivaut

- les expression conditionnelles en utilisant <code>true</code> comme expression soumis.
+ <code>true</code> comme expression soumise pour gérer les expressions conditionnelles.

2021-03-11 11:11 UTC, SVGAnimate reviewed
(Test review)
"Cette clause correspond à tout ce qui ne correspondait pas auparavant."
"Cette clause est évaluée si aucune clause précédente n'a été vérifiée."

2021-03-11 11:12 UTC, SVGAnimate commented on language/control-structures/match.xml
> +  <title>Exemple d'embranchement manquant</title>
J'ai tout cassé :-(

2021-03-11 12:25 UTC, Girgias commented on language/control-structures/match.xml
> +  <title>Exemple d'embranchement manquant</title>
Absent fait du sens

2021-03-11 12:29 UTC, Girgias commented
> Si il vous plaît, dites moi comment ajouter une suggestion sur github ?
> 
>     * Cette clause est évalué si aucune clause précédente correspondait à la condition fourni.
> 
> 
>     * Cette clause est évaluée si aucune clause précédente n'a correspondu.
> 
> 
> -Equivalent
> +Equivaut
> 
>     * les expression conditionnelles en utilisant `true` comme expression soumis.
> 
> 
>     * `true` comme expression soumise pour gérer les expressions conditionnelles.
Quand tu ajoutes un commentaire sur une ligne de code, l'icône la plus à gauche avant le formatage, (le rectange avec un +/-) va t'inséré qqch du genre:
```
```suggestion
  <title>Exemple d'embranchement manquant</title>
.```
```
Où tu écris les modifications que tu veux suggérer, donc si tu veux suggérer l'utilisation du mot `absent`:


```
```suggestion
  <title>Exemple d'embranchement absent</title>
.```
```

2021-03-11 12:54 UTC, SVGAnimate commented on language/control-structures/match.xml
> +  <title>Exemple d'embranchement manquant</title>
```suggestion
  <title>Exemple d'embranchement absent</title>
.```
(Test : Avec un petit merci en commentaire)

2021-03-11 12:56 UTC, SVGAnimate commented on language/control-structures/match.xml
> +  <title>Exemple d'embranchement manquant</title>
```suggestion
  <title>Exemple d'embranchement absent</title>

2021-03-11 13:08 UTC, SVGAnimate commented on language/control-structures/match.xml
> +  <title>Exemple d'embranchement manquant</title>
(Test de commentaire)

2021-05-23 09:50 UTC, SVGAnimate reviewed
Ais-je oublié de cliquer sur Submit review ?

2021-05-23 09:52 UTC, SVGAnimate commented on language/control-structures/match.xml
> +  Cette clause correspond à tout ce qui ne correspondait pas auparavant.
Mince, il manque un espace devant "Cette clause"

2021-05-23 10:02 UTC, closed without merging

2021-05-23 10:04 UTC, SVGAnimate commented
C'est le fouillis. Je recommence un PR.