Apply 615dc682cf741edd7fbb40bd7b20c43f1e6c3940
php/doc-fr pull request #204
Opened 2022-04-15 07:55 UTC by eugene-augier

2022-04-15 17:33 UTC, Girgias requested changes

2022-04-15 17:33 UTC, Girgias commented on install/fpm/configuration.xml
> +        Valeur par défaut : no. Depuis PHP 7.3.0.
```suggestion
        Valeur par défaut : no. À partir de PHP 7.3.0.
```

2022-04-15 17:33 UTC, Girgias commented on install/fpm/configuration.xml
> +        Valeur par défaut : 20. Depuis PHP 7.2.0.
```suggestion
        Valeur par défaut : 20. À partir de PHP 7.2.0.
```

2022-04-15 17:33 UTC, Girgias commented on install/fpm/configuration.xml
> +        <literal>pm</literal> est défini sur <literal>dynamic</literal>.
```suggestion
        <literal>pm</literal> est défini à <literal>dynamic</literal>.
```
Plutôt non?

2022-04-15 17:46 UTC, eugene-augier commented
J'ai fix direct depuis github @Girgias

2022-04-19 23:40 UTC, merged

2022-04-19 23:40 UTC, Girgias commented
Merci!