Sync various sections
php/doc-fr pull request #270
Opened 2022-08-16 09:40 UTC by saundefined

2022-08-16 21:00 UTC, devnexen commented on reference/strings/functions/utf8-encode.xml
> +        Cette fonction a été rendu obsolète.
rendu => rendue but I see the issue in other places too.

2022-08-17 05:31 UTC, saundefined commented on reference/strings/functions/utf8-encode.xml
> +        Cette fonction a été rendu obsolète.
Thanks for the review! Fixed =)

2022-08-17 17:28 UTC, adoy requested changes

2022-08-17 17:28 UTC, adoy commented on reference/datetime/datetimeinterface/format.xml
> +            Une représentation numérique complète étendue d'une année, au moins 4 chiffres,
```suggestion
            Une représentation numérique complète étendue d'une année, d'au moins 4 chiffres,
```

2022-08-17 17:28 UTC, adoy commented on reference/datetime/datetimeinterface/format.xml
> +            avec <literal>-</literal> pour les années avant de l'ère commune
```suggestion
            avec <literal>-</literal> pour les années avant l'ère commune
```

2022-08-17 18:00 UTC, devnexen commented
I see nothing really wrong left but maybe @Girgias would like to have a look

2022-08-17 20:27 UTC, adoy approved these changes

2022-08-18 12:10 UTC, Girgias commented on reference/datetime/datetimeinterface/format.xml
> +            et <literal>+</literal> pour les années de l'ère commune.
```suggestion
            avec un <literal>-</literal> pour les années avant l'ère commune
            et ubn <literal>+</literal> pour les années de l'ère commune.
```

2022-08-18 12:11 UTC, merged