Sync various section
php/doc-fr pull request #293
Opened 2022-10-10 19:04 UTC by victor-prdh

Hi, just a little question:
`reference/classobj/functions/is-a.xml` seems not very logical, even in the doc-en. It'sspeak about "object type" and "class" for the same things, it's maybe better to keep only one of those (l.17) ?

Summary: 
* Sync appendice/reserved

* Sync predefined/interfaces

* Sync types/object

* Sync classobj/functions

* Sync info/functions

Thanks for your review !

2022-10-10 19:08 UTC, devnexen commented
> Hi, just a little question: `reference/classobj/functions/is-a.xml` seems not very logical, even in the doc-en. It'sspeak about "object type" and "class" for the same things, it's maybe better to keep only one of those (l.17) ?

If that's the case, maybe you need to open a PR in doc-en first ?

2022-10-10 20:07 UTC, victor-prdh commented
Yes, i think i will do that, it was just to have other notices on this subject. I Draft this PR in wait for the doc-en. Thanks

2022-10-11 20:55 UTC, Girgias requested changes

2022-10-11 20:55 UTC, Girgias commented on language/predefined/interfaces.xml
> +<!-- Reviewed: no -->
Do not update the Maintainer tag just for doing a 1 line diff update.

2022-10-16 13:01 UTC, victor-prdh commented on language/predefined/interfaces.xml
> +<!-- Reviewed: no -->
Oh sorry, i put yannick back !

2022-12-10 08:51 UTC, closed without merging