Sync various Date related files
php/doc-fr pull request #320
Opened 2022-12-21 20:00 UTC by victor-prdh

Hi everyone,
Some work on the date section
Thanks for your review
cheers

2022-12-21 20:08 UTC, victor-prdh commented
sorry, didn't have time to translate `reference/datetime/datetimeinterface/format.xml`, i just fix the link for now

2022-12-24 13:05 UTC, Girgias requested changes
Other the one issue looks good

2022-12-24 13:05 UTC, Girgias commented on reference/datetime/datetime/construct.xml
> +  </methodsynopsis>
Wrong class as this should be about ``DateTime`` and not ``DateTimeImmutable``

Actual diff: http://doc.php.net/revcheck.php?p=plain&lang=fr&hbp=eeeb152d8a3f41463148e87e0c048c4fb168f292&f=reference/datetime/datetime/construct.xml&c=on

2022-12-24 15:23 UTC, victor-prdh commented on reference/datetime/datetime/construct.xml
> +  </methodsynopsis>
Oh yes my bad ! it's now fixed

2022-12-25 09:49 UTC, Girgias requested changes

2022-12-25 09:49 UTC, Girgias commented on reference/datetime/datetime/construct.xml
> +  </methodsynopsis>
Again please revert this as this is *not* how the English page is

2022-12-25 10:57 UTC, victor-prdh commented on reference/datetime/datetime/construct.xml
> +  </methodsynopsis>
omg, just understand what did i do... sorry i don't know from where i translated this

2022-12-26 02:03 UTC, Girgias approved these changes

2022-12-26 02:03 UTC, merged

2022-12-26 02:03 UTC, Girgias commented
Thank you!