Fix some typos
php/doc-fr pull request #33
Opened 2021-04-20 17:13 UTC by landrok

2021-04-20 17:36 UTC, Girgias requested changes
À part deux trucs, ceci est O.K.

Merci :-)

2021-04-20 17:36 UTC, Girgias commented on appendices/migration71/other-changes.xml
> +   Les IDs de session ne seront plus hashés dès la génération. Avec ce changement
```suggestion
   Les IDs de session ne seront plus hachés dès la génération. Avec ce changement
```
Car la traductiont de "to hash" normalement c'est "hacher" selon notre fichier TRADUCTION

2021-04-20 17:36 UTC, Girgias commented on appendices/migration72/new-features.xml
> +   plus large de formats. Cela signifie que ses balises spécifiques au
```suggestion
   plus large de formats. Cela signifie que ces balises spécifiques au 
```
C'est pas plutôt "ces" balises ici?

2021-04-20 17:36 UTC, Girgias commented on appendices/userlandnaming.xml
> +     les noms des classes utilisent les notations <literal>camelCase</literal>
Faut pas changer ça, une rectification doit être proposé upstream (version EN) pour peut être changer ceci en "PascalCase".

2021-04-21 11:35 UTC, landrok commented on appendices/userlandnaming.xml
> +     les noms des classes utilisent les notations <literal>camelCase</literal>
```xml
    <para>
     Les noms des fonctions utilisent un underscore entre les mots, tandis que
     les noms des classes utilisent les notations <literal>CamelCase</literal>
     et <literal>PascalCase</literal>.
    </para>
```

Le PascalCase est également mentionné à la ligne suivante. Je suis d'accord avec toi dans le sens où les nommages "récents" et les recommandations des PHP-FIG vont vers un nommage des classes en PascalCase mais historiquement, il y a encore des classes PHP core qui sont en camelCase (streamWrapper).

PI la typo avait été corrigée dans doc-en: 
```xml
    <para>
     Function names use underscores between words, while class names use
     both the <literal>camelCase</literal> and <literal>PascalCase</literal>
     rules.
    </para>
```

Qu'est-ce que tu en penses ? Est-ce qu'on fait la proposition de modif sur le upstream ?

2021-04-21 13:22 UTC, Girgias commented on appendices/userlandnaming.xml
> +     les noms des classes utilisent les notations <literal>camelCase</literal>
J'avais pas vu la mention du PascalCase juste en dessous, ça m'apprendra à aller trop vite.
Après le truc c'est que en PHP les noms de classes sont insensible à la case donc tu peux les appeller n'importe comment, et le plus commun etant stdClass et la dernière fois qu'une normalisation a été discuté les gens avait pas l'air fifou, mais après le détail que les noms de classes sont pas sensible à la case était pas mentionner.
à voir donc

2021-04-21 14:49 UTC, landrok commented on appendices/userlandnaming.xml
> +     les noms des classes utilisent les notations <literal>camelCase</literal>
Pour le coup, je ne vais pas être téméraire et me pointer sur le upstream la fleur au fusil pour relancer le débat. Dans un premier temps, je me suis fixé comme objectif de faire une repasse sur l'orthographe et la grammaire de toute la doc-fr.

Bien vu pour stdClass, j'étais parti loin pour chercher du camelCase alors qu'il y en avait sous mes yeux :)

Merci pour les précisions sur le core pour le côté case-insensitive des noms de classe. A force de penser PSR-4 dans le userland, les namespaces étant adossés au filesystem (case-sensitive sauf win32) et les classes "autoloadées", je n'avais même pas regardé dans le core ce qu'il en était.

De mon côté, c'est OK pour la repasse sur /appendices/.

2021-04-27 14:43 UTC, Girgias commented
Tu peux squash rebase sur master vite fait?

2021-04-27 16:58 UTC, landrok commented
Fait, j'ai fait un merge avant le push pour éviter de faire un force, pas trop grave pour l'historique ?

2021-04-27 17:51 UTC, Girgias commented
> Fait, j'ai fait un merge avant le push pour éviter de faire un force, pas trop grave pour l'historique ?

Je préfère un rebase avec un force push vu que c'est ce que je vais faire quand je merge (pour éviter les merges commits).

C'est pas grave de force push sur ta propre branche :-)

2021-04-28 11:39 UTC, landrok commented
Si ce n'est pas grave, alors je force push ;)

Le squash rebase est fait avec son force push.

2021-04-28 11:51 UTC, merged