Handle deleted/moved files from english documentation
php/doc-fr pull request #357
Opened 2023-02-18 15:53 UTC by adoy

Fixes #356

2023-02-18 19:03 UTC, Girgias requested changes
Other than the <type> issue LGTM from a quick review

2023-02-18 19:03 UTC, Girgias commented on reference/random/constants.xml
> +     (<type>entier</type>)
```suggestion
     (<type>int</type>)
```

Please do not translate types within the ``<type>`` tags as those are used to generate links.

2023-02-18 19:31 UTC, devnexen commented on reference/reflection/reflectionfunctionabstract/isstatic.xml
> +       Cette méthode a été remontée. Auparavant, elle était uniquement définie dans
`remontée`. I guess you mean `retirée`

2023-02-19 04:35 UTC, adoy commented on reference/reflection/reflectionfunctionabstract/isstatic.xml
> +       Cette méthode a été remontée. Auparavant, elle était uniquement définie dans
No. It was previously on the `ReflectionMethod` and it was pulled up in the class hierarchy.

2023-02-19 04:48 UTC, adoy commented on reference/random/constants.xml
> +     (<type>entier</type>)
Thanks @Girgias. I'm not sure `<type>` is used to generate link (at least not on [this page](https://www.php.net/manual/en/random.constants.php)) but nonetheless I'm ok with not translating those. I grepped the french doc and find some `<type>Tableau</type>`, `<type>chaîne de caractères</type>`, etc. I'll probably at some point do a commit to fix them.

2023-02-19 05:02 UTC, devnexen commented on reference/reflection/reflectionfunctionabstract/isstatic.xml
> +       Cette méthode a été remontée. Auparavant, elle était uniquement définie dans
My bad you re right

2023-02-19 14:09 UTC, merged

2023-02-19 18:09 UTC, Girgias commented on reference/random/constants.xml
> +     (<type>entier</type>)
Yeah... known bug that at some point PhD broke and it stopped generating the links for int,float,bool,array, and string. But it does for ``<type>callable</type>``, ``<type>void</type>`` and others