prefedfined server vars sync
php/doc-fr pull request #379
Opened 2023-03-05 08:56 UTC by devnexen

2023-03-05 22:55 UTC, adoy approved these changes

2023-03-06 02:30 UTC, Girgias requested changes

2023-03-06 02:30 UTC, Girgias commented on language/predefined/variables/server.xml
> +<!-- EN-Revision: b767006c8672c9e8ecec8429bb4f3be8889bde6b Maintainer: yannick Status: ready -->
This doesn't properly sync with: http://doc.php.net/revcheck.php?p=plain&lang=fr&hbp=cdaea0421544885f02ff3d36bd203dc01b78299e&f=language/predefined/variables/server.xml&c=on

A bunch of personalisation is still present that needs to be double checked.

2023-03-09 06:55 UTC, Girgias approved these changes
Missing the update on line 91 for ``Par exemple '<literal>CGI/1.1</literal>'.`` to ``Par exemple <literal>'CGI/1.1'</literal>.`` but then it is up to date.

Thank you again!

2023-03-09 07:18 UTC, merged