Translate language/types
php/doc-fr pull request #424
Opened 2023-03-26 18:19 UTC by adoy

2023-03-26 21:17 UTC, Girgias requested changes
Quelque nits

2023-03-26 21:17 UTC, Girgias commented on language/types/never.xml
> +  <type>never</type> est, dans le langage de la théorie des types, le type inférieur.
```suggestion
  <type>never</type> est, dans le langage de la théorie des types, le type vide.
```
c.f. https://fr.wikipedia.org/wiki/Type_vide

2023-03-26 21:17 UTC, Girgias commented on language/types/numeric-strings.xml
> +   en <emphasis>fin</emphasis> de chaîne, la chaîne était considérée comme numérique.
Plutôt non? Car sinon les deux phrases se contredisent.
```suggestion
   en <emphasis>fin</emphasis> de chaîne, la chaîne était considérée comme non numérique.
```

2023-03-26 21:17 UTC, Girgias commented on language/types/type-system.xml
> +       <simpara><type>null</type> type</simpara>
J'ai l'impression que mettre "type" avant se lit mieux
```suggestion
       <simpara>type <type>null</type></simpara>
```

2023-03-27 00:03 UTC, adoy commented on language/types/numeric-strings.xml
> +   en <emphasis>fin</emphasis> de chaîne, la chaîne était considérée comme numérique.
En fait je viens de voir l'anglais c'est 
> leading numeric
Je suis pas sur de comment bien traduire ça.

2023-03-27 22:13 UTC, Girgias commented on language/types/numeric-strings.xml
> +   en <emphasis>fin</emphasis> de chaîne, la chaîne était considérée comme numérique.
Heu... je pense qu'on va devoir écrire qqch de plus long genre "chaîne débutant numériquement" pour "leading numeric"

2023-03-29 13:49 UTC, Girgias commented on language/types/numeric-strings.xml
> +  PHP dispose également d'un concept de chaînes à <emphasis>tête</emphasis> numérique.
Il reste ici à adresser la terminologie

2023-03-29 23:44 UTC, Girgias approved these changes

2023-03-30 12:56 UTC, merged