soap sync
php/doc-fr pull request #431
Opened 2023-04-02 15:26 UTC by devnexen

2023-04-02 16:05 UTC, adoy requested changes
J'ai fait une première passe rapide. Je referais une autre passe plus en détail après. 
Merci si tu peux marquer les différents commentaires à `resolved` une fois que tu les a appliqué ça aide pour le review.

Merci encore :)

2023-04-02 16:05 UTC, adoy commented on reference/soap/constants.xml
> +      partie de <link linkend="soapclient.construct.options.compression">
Les "as part of" sont traduit de façon différentes dans les options. Est-ce que ce serais possible de consolider ça dans le document ? Merci :)

2023-04-02 16:05 UTC, adoy commented on reference/soap/constants.xml
> +      l'option <literal>style</literal> à <methodname>SoapClient::__construct</methodname>.
```suggestion
      qu'option <literal>style</literal> à <methodname>SoapClient::__construct</methodname>.
```

2023-04-02 16:05 UTC, adoy commented on reference/soap/constants.xml
> +      Utilisé avec l'option dépréciée
Féminin

2023-04-02 16:05 UTC, adoy commented on reference/soap/constants.xml
> +      Utilisé avec l'option <link linkend="soapclient.construct.options.ssl-method">
Féminin

2023-04-02 16:05 UTC, adoy commented on reference/soap/constants.xml
> +     Utilisé avec l'option dépréciée <link linkend="soapclient.construct.options.ssl-method">
Féminin

2023-04-02 16:05 UTC, adoy commented on reference/soap/constants.xml
> +     Utilisé avec l'option dépréciée <link linkend="soapclient.construct.options.ssl-method">
Féminin et même chose pour les autres :)

2023-06-14 03:24 UTC, adoy commented
@devnexen La build ne semble pas passer sur ta branche.

2023-06-14 18:57 UTC, devnexen commented
oh I see, soapclient/construct.xml is out of sync..

2023-06-18 12:52 UTC, Girgias requested changes
Je suis pas hyper fan du partial sync de SoapClient::__construct() ça a l'air de quasiment mettre à jour sauf pour qq trucs et donc faire la review est dificille

Les deux autres pages sont grosso-modo OK

2023-06-18 12:52 UTC, Girgias commented on reference/soap/constants.xml
> +      Spécifie l'utilisation du codage SOAP lorsqu'elle est passée en tant qu'option
```suggestion
      Spécifie l'utilisation de l'encodage SOAP lorsqu'elle est passée en tant qu'option
```

2023-06-18 12:52 UTC, Girgias commented on reference/soap/constants.xml
> +      Spécifie l'utilisation d'un codage spécifique au service lorsqu'elle est passée en tant
```suggestion
      Spécifie l'utilisation d'un encodage spécifique au service lorsqu'elle est passée en tant
```

2023-06-18 12:52 UTC, Girgias commented on reference/soap/constants.xml
> +      Spécifie l'utilisation de l'authentification HTTP Basic lorsqu'elle est passée
```suggestion
      Spécifie l'utilisation de l'authentification HTTP basique lorsqu'elle est passée
```
@adoy plutôt, non?

2023-06-18 13:58 UTC, adoy commented on reference/soap/constants.xml
> +      Spécifie l'utilisation de l'authentification HTTP Basic lorsqu'elle est passée
@Girgias Je sais pas je me pose la question. Si ca avait était Digest est-ce qu'on l'aurait traduit ?

2023-06-18 14:00 UTC, adoy commented on reference/soap/constants.xml
> +      Utilisé avec l'option dépréciée
deprecated = obsolète

2023-06-27 00:06 UTC, Girgias commented on reference/soap/constants.xml
> +      Spécifie l'utilisation de l'authentification HTTP Basic lorsqu'elle est passée
En effet on aurait pas traduit, donc bon de laisser.

2023-06-27 00:27 UTC, Girgias approved these changes
Bon y a des problèmes de cohérences entre les phrases et d'intentation, mais je pense merge en état actuel car ça va être un bordel sinon et ça sera plus simple de fix les trucs dans des PRs plus petites.

2023-06-27 00:27 UTC, Girgias commented on reference/soap/soapclient/construct.xml
> +           l'authentification de base est utilisée.
```suggestion
           l'authentification basique est utilisée.
```
Plutôt je pense

2023-06-27 00:27 UTC, Girgias commented on reference/soap/soapclient/construct.xml
> +           Nom d'utilisateur à utiliser avec l'authentification de base ou l'authentification par hachage.
Je pense que si on traduit pas HTTP Basic ni HTTP Digest vaut mieux les utiliser tel quel ici, qu'en pense tu @adoy ?

2023-06-27 00:27 UTC, Girgias commented on reference/soap/soapclient/construct.xml
> +           Mot de passe à utiliser avec l'authentification de base ou l'authentification par hachage.
Ditto

2023-06-27 00:27 UTC, Girgias commented on reference/soap/soapclient/construct.xml
> +           qui est utilisé pour l'authentification de base ou l'authentification digest.
Ditto

2023-06-27 00:27 UTC, Girgias commented on reference/soap/soapclient/construct.xml
> +           de base HTTP.
Ditto

2023-06-27 00:27 UTC, Girgias commented on reference/soap/soapclient/construct.xml
> +           de type objet et renvoyant une chaîne de caractères).
Rien à voir avec la traduction, mais franchement la doc EN devrait juste avoir le markup des signatures comme on le fait pour les callables de tri, et autre. Enfin ça c'est future scope.

2023-06-27 00:27 UTC, Girgias commented on reference/soap/soapclient/construct.xml
> +         <varlistentry xml:id="soapclient.construct.options.user-agent">
```suggestion
           Si non spécifié, l'option de configuration <link linkend="ini.soap.wsdl-cache">
           soap.wsdl_cache</link> sera utilisée.
          </para>
         </listitem>
        </varlistentry>
        <varlistentry xml:id="soapclient.construct.options.user-agent">
```

C'est le début des problèmes d'intentation ici, mais je pense que ça sera plus simple de fix après que ceci est merge car la diff est immense

2023-06-27 00:27 UTC, Girgias commented on reference/soap/soapclient/construct.xml
> +                 contenant un schéma pour la réponse. Consultez la section Exemples pour une illustration.
```suggestion
                 contenant un schéma pour la réponse. Consultez la section des examples pour une illustration.
```

2023-06-27 00:27 UTC, Girgias commented on reference/soap/soapclient/construct.xml
> +              Notez que les versions SSL 2 et 3 sont considérées comme non sécurisées et peuvent ne pas être prises en charge par la bibliothèque OpenSSL installée.
```suggestion
              Il est à noter que les versions SSL 2 et 3 sont considérées comme non sécurisées et peuvent ne pas être prises en charge par la bibliothèque OpenSSL installée.
```

2023-06-27 00:27 UTC, Girgias commented on reference/soap/soapclient/construct.xml
> +              Cette option est <emphasis>obsolète</emphasis> depuis PHP 8.1.0.
```suggestion
              Cette option est <emphasis>obsolète</emphasis> à partir de PHP 8.1.0.
```

2023-06-27 00:27 UTC, Girgias commented on reference/soap/soapclient/construct.xml
> +        <methodname>SoapClient::__construct</methodname> example
```suggestion
        Example <methodname>SoapClient::__construct</methodname>
```

2023-06-27 00:27 UTC, Girgias commented on reference/soap/soapclient/construct.xml
> +    <title>Using the <constant>SOAP_SINGLE_ELEMENT_ARRAYS</constant> feature</title>
```suggestion
    <title>Utilisant la fonctionalité  <constant>SOAP_SINGLE_ELEMENT_ARRAYS</constant></title>
```

2023-06-27 00:31 UTC, merged

2023-06-27 13:02 UTC, adoy commented on reference/soap/soapclient/construct.xml
> +           Nom d'utilisateur à utiliser avec l'authentification de base ou l'authentification par hachage.
Je suis d'accord.