Fix small typos in doc-fr root files
php/doc-fr pull request #5
Opened 2021-01-01 20:08 UTC by ici-be

2021-01-01 20:14 UTC, villfa commented on README.txt
> +Le caractère d'indentation est une espace (aucune tabulation n'est admise dans les fichiers .xml)
to revert

2021-01-01 22:16 UTC, orklah commented on README.txt
> +Le caractère d'indentation est une espace (aucune tabulation n'est admise dans les fichiers .xml)
What would be the rationale? The term "une" is grammatically more correct in this context. I'd agree that this isn't widely used and a very opiniated syntax also this document use a very relaxed tone so this could stay as is though

2021-01-01 22:29 UTC, villfa commented on README.txt
> +Le caractère d'indentation est une espace (aucune tabulation n'est admise dans les fichiers .xml)
The term "une" is used before feminine words but "espace" is masculine: https://www.larousse.fr/dictionnaires/francais/espace/31013

2021-01-01 22:30 UTC, villfa commented on README.txt
> + - faire des messages en anglais (au cas où un non-francophone a besoin de comprendre les modifications)
```suggestion
 - faire des messages en anglais (au cas où un non-anglophone a besoin de comprendre les modifications)
```

2021-01-01 22:32 UTC, villfa commented on README.txt
> +Le caractère d'indentation est une espace (aucune tabulation n'est admise dans les fichiers .xml)
This sounds even better that way:
```suggestion
Le caractère d'indentation est l'espace (aucune tabulation n'est admise dans les fichiers .xml)
```

2021-01-01 22:43 UTC, orklah commented on README.txt
> +Le caractère d'indentation est une espace (aucune tabulation n'est admise dans les fichiers .xml)
The term "espace" is used in a typography context here. In this context, the noun is feminine: https://www.larousse.fr/dictionnaires/francais/espace/31014
I agree that `l'` get rid of the ambiguity

2021-01-02 16:15 UTC, Girgias commented on README.txt
> +Le caractère d'indentation est une espace (aucune tabulation n'est admise dans les fichiers .xml)
Huh, TIL.
Could this be updated to use ``l'`` before I merge?

2021-01-02 16:15 UTC, Girgias requested changes
Nit pointed out in comment

2021-01-04 07:30 UTC, ici-be commented
Thanks for the " l' " suggestion (indeed, "une" was a bit formal), I approved it

2021-01-05 14:47 UTC, villfa approved these changes

2021-01-05 23:00 UTC, closed without merging