classobj section sync
php/doc-fr pull request #552
Opened 2023-07-11 20:37 UTC by devnexen

2023-07-12 04:11 UTC, Girgias requested changes
Appliquer les modifications du fichier ``get-called-class.xml`` à ``get-class.xml`` ce qui était le but des commits de doc-en

2023-07-12 04:11 UTC, Girgias commented on reference/classobj/functions/get-called-class.xml
> +   une <classname>Error</classname> est levée. Avant PHP 8.0.0,
```suggestion
   une <classname>Error</classname> est lancé. Antérieur à PHP 8.0.0,
```

2023-07-12 04:11 UTC, Girgias commented on reference/classobj/functions/get-called-class.xml
> +        lèvera maintenant une <classname>Error</classname>.
```suggestion
        lance désormais une <classname>Error</classname>.
```

2023-07-26 14:03 UTC, Girgias commented on reference/classobj/functions/get-called-class.xml
> +       </entry>
This wording should be synced with the wording in ``get_class()`` as those are currently different

2023-07-26 20:49 UTC, Girgias commented on reference/classobj/functions/get-called-class.xml
> +        &false;.
En soit je préférais la version que tu avais faite avant, juste je voulais que tu la copie sur la page de get_class :')

2023-07-26 20:51 UTC, devnexen commented on reference/classobj/functions/get-called-class.xml
> +        &false;.
ah ok :-D

2023-07-26 20:59 UTC, merged